name: Generate xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        
    - name: Generate the sitemap
      id: sitemap22
      uses: cicirello/generate-sitemap@v1.10.2
      with:
        base-url-path: https://github.com/moblifeapps/myweb
        include-pdf: false
        sitemap-format: xml
        path-to-root: uploads

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
